# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from Gyro_sensor/Gyro_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Gyro_msg(genpy.Message):
  _md5sum = "fb2bb114d1e350ea2deb434716fc40d9"
  _type = "Gyro_sensor/Gyro_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 a_x
float32 a_y
float32 a_z

float32 w_x
float32 w_y
float32 w_z

float32 an_x
float32 an_y
float32 an_z
"""
  __slots__ = ['a_x','a_y','a_z','w_x','w_y','w_z','an_x','an_y','an_z']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a_x,a_y,a_z,w_x,w_y,w_z,an_x,an_y,an_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Gyro_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.a_x is None:
        self.a_x = 0.
      if self.a_y is None:
        self.a_y = 0.
      if self.a_z is None:
        self.a_z = 0.
      if self.w_x is None:
        self.w_x = 0.
      if self.w_y is None:
        self.w_y = 0.
      if self.w_z is None:
        self.w_z = 0.
      if self.an_x is None:
        self.an_x = 0.
      if self.an_y is None:
        self.an_y = 0.
      if self.an_z is None:
        self.an_z = 0.
    else:
      self.a_x = 0.
      self.a_y = 0.
      self.a_z = 0.
      self.w_x = 0.
      self.w_y = 0.
      self.w_z = 0.
      self.an_x = 0.
      self.an_y = 0.
      self.an_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.a_x, _x.a_y, _x.a_z, _x.w_x, _x.w_y, _x.w_z, _x.an_x, _x.an_y, _x.an_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.a_x, _x.a_y, _x.a_z, _x.w_x, _x.w_y, _x.w_z, _x.an_x, _x.an_y, _x.an_z,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.a_x, _x.a_y, _x.a_z, _x.w_x, _x.w_y, _x.w_z, _x.an_x, _x.an_y, _x.an_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.a_x, _x.a_y, _x.a_z, _x.w_x, _x.w_y, _x.w_z, _x.an_x, _x.an_y, _x.an_z,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
